import { useEffect, useState, type ReactNode } from 'react';
import { calloutTemplates, normalizeHex, type CalloutNote, type CalloutStyle, type CalloutTemplate } from '../calloutTypes';
import { uid, type EditorState } from './storage';
import { Field, InlineText, Segmented, Toggle } from './ui';

export function Note({ type, state, children }: { type: string; state: EditorState; children: ReactNode }) {
  const settings = calloutTemplates(state.callouts).find(item => item.id === type);
  if (!settings) return null;
  return <div className="cms-note" style={{ background: `color-mix(in srgb, ${settings.color} ${settings.backgroundOpacity}, transparent)` }}><span className="note-icon">{settings.icon}</span><div><strong style={{ color: settings.color }}>{settings.title}</strong>{children}</div></div>;
}
export function HexInput({ value, onChange }: { value: string; onChange: (color: string) => void }) {
  const [draft, setDraft] = useState(value), [editing, setEditing] = useState(false);
  useEffect(() => { if (!editing) setDraft(value); }, [value, editing]);
  const valid = normalizeHex(draft);
  return <div className="hex-field"><div className="color-input"><span className="color-swatch" style={{ background: valid ?? value }} /><input className="hex-input" type="text" aria-label="HEX цвет" aria-invalid={!valid} value={draft} maxLength={7} autoComplete="off" spellCheck={false} onFocus={() => setEditing(true)} onChange={event => { setDraft(event.target.value); const color = normalizeHex(event.target.value); if (color) onChange(color); }} onBlur={() => { if (valid) { setDraft(valid); setEditing(false); } }} /></div>{!valid && <small className="field-error">Введи HEX: #F9C02F или #FC0</small>}</div>;
}
export function ExtraNotes({ notes, state, position }: { notes?: CalloutNote[]; state: EditorState; position: 'before' | 'after' }) {
  return notes?.filter(note => note.enabled !== false && note.position === position).map(note => <Note key={note.id} type={note.templateId} state={state}><p>{note.text}</p></Note>);
}
export function NotesEditor({ notes = [], state, onChange }: { notes?: CalloutNote[]; state: EditorState; onChange: (notes: CalloutNote[]) => void }) {
  const [adding, setAdding] = useState(false);
  const templates = calloutTemplates(state.callouts);
  const update = (id: string, patch: Partial<CalloutNote>) => onChange(notes.map(note => note.id === id ? { ...note, ...patch } : note));
  return <div className="extra-notes-editor"><div className="notes-editor-heading"><span>Дополнительные плашки</span><button type="button" className="quiet-button" onClick={() => setAdding(!adding)} aria-expanded={adding}>+ Добавить плашку</button></div>{adding && <div className="callout-picker">{templates.map(template => <button type="button" key={template.id} onClick={() => { onChange([...notes, { id: uid(), templateId: template.id, text: '', enabled: true, position: 'after' }]); setAdding(false); }}><span style={{ background: `color-mix(in srgb, ${template.color} ${template.backgroundOpacity}, transparent)` }}>{template.icon}</span><strong>{template.title}</strong></button>)}</div>}{notes.map(note => <section className={`extra-note${note.enabled === false ? ' is-disabled' : ''}`} key={note.id}><div className="extra-note-controls"><select aria-label="Шаблон плашки" value={note.templateId} onChange={event => update(note.id, { templateId: event.target.value })}>{templates.map(template => <option key={template.id} value={template.id}>{template.icon} {template.title}</option>)}</select><button type="button" className="quiet-button" aria-label="Удалить плашку" onClick={() => onChange(notes.filter(item => item.id !== note.id))}>Удалить</button><Toggle label="Показывать плашку" checked={note.enabled !== false} onChange={enabled => update(note.id, { enabled })} /></div><Segmented label="Положение плашки" value={note.position} onChange={position => update(note.id, { position })} options={[{ value: 'before', label: 'Перед текстом' }, { value: 'after', label: 'После текста' }]} /><Note state={state} type={note.templateId}><InlineText label="Текст плашки" value={note.text} onChange={text => update(note.id, { text })} /></Note></section>)}</div>;
}
export function CalloutSettings({ state, onChange }: { state: EditorState; onChange: (state: EditorState) => void }) {
  const templates = calloutTemplates(state.callouts);
  const update = (id: string, patch: Partial<CalloutStyle>) => onChange({ ...state, callouts: id === 'hypothesis' || id === 'test' ? { ...state.callouts, [id]: { ...state.callouts[id], ...patch } } : { ...state.callouts, custom: (state.callouts.custom ?? []).map(item => item.id === id ? { ...item, ...patch } : item) } });
  const add = () => { const template: CalloutTemplate = { id: uid(), title: 'Новая плашка', icon: '✦', color: '#B69BFF', backgroundOpacity: '16%' }; onChange({ ...state, callouts: { ...state.callouts, custom: [...(state.callouts.custom ?? []), template] } }); };
  return <section className="cms-settings"><div className="settings-row"><h1>Плашки</h1><button type="button" className="add-block-button" onClick={add}>+ Новый шаблон</button></div>{templates.map(settings => { const fixed = settings.id === 'hypothesis' || settings.id === 'test'; const used = state.cases.some(project => project.sections.some(section => section.notes?.some(note => note.templateId === settings.id))); return <section className="callout-settings" key={settings.id}><div className="settings-row callout-template-heading"><h2>{settings.title}</h2>{!fixed && <button type="button" className="quiet-button" disabled={used} title={used ? 'Шаблон используется в кейсе' : undefined} onClick={() => onChange({ ...state, callouts: { ...state.callouts, custom: (state.callouts.custom ?? []).filter(item => item.id !== settings.id) } })}>Удалить шаблон</button>}</div><div className="callout-settings-grid"><Field label="Иконка"><input className="emoji-input" aria-label="Иконка плашки" value={settings.icon} onChange={event => update(settings.id, { icon: event.target.value })} /></Field><Field label="Заголовок"><InlineText label="Заголовок плашки" value={settings.title} onChange={title => update(settings.id, { title })} /></Field><Field label="Цвет HEX"><HexInput value={settings.color} onChange={color => update(settings.id, { color })} /></Field><Field label={`Плотность фона · ${settings.backgroundOpacity}`}><input type="range" min={0} max={50} aria-label="Плотность фона" value={parseFloat(settings.backgroundOpacity)} onChange={event => update(settings.id, { backgroundOpacity: `${event.target.value}%` })} /></Field></div><Note state={state} type={settings.id}><p>Так будет выглядеть плашка в кейсе. Цвет заголовка и фона связан, а прозрачность регулируется отдельно.</p></Note></section>; })}</section>;
}
